request_type: "citizenship" #this value should be either "citizenship" or "passport"
# Only use the following if using for passport:
has_under_age_children: "No" #Yes or No
total_children: "0" # Total number of children
possess_expired_passport: "No" # Yes or No
full_address: "Your full adress should be placed here" # Full residential address
marital_status: ""